In [1]:
import pandas as pd
from scipy.stats import zscore

In [2]:
df = pd.read_csv("fer2018PixelSplitRandomize.csv");

In [3]:
df.head()

,emotion,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel2295,pixel2296,pixel2297,pixel2298,pixel2299,pixel2300,pixel2301,pixel2302,pixel2303,pixel2304
0,4,176,158,143,131,119,142,143,133,137,...,164,162,160,167,177,165,85,22,52,97
1,2,100,110,117,121,125,125,126,128,128,...,172,166,159,155,153,150,148,149,136,135
2,6,48,47,43,32,23,34,28,21,24,...,47,39,26,11,15,24,26,22,53,74
3,1,93,99,93,78,87,52,54,102,122,...,159,139,140,156,162,117,80,101,109,113
4,4,174,173,161,136,169,117,133,158,158,...,194,217,201,168,153,145,70,153,213,211

In [4]:
index_df = df["emotion"]
df = df.drop(["emotion"], axis=1)

In [5]:
df = df.apply(zscore)

In [6]:
df.insert(0, "emotion", index_df)
df = df.set_index("emotion")

In [7]:
df.to_csv("fer2018PixelSplitRandomizeZscore.csv");